"""Target types for package_v2_shell_command."""

from pants.engine.target import (
    COMMON_TARGET_FIELDS,
    BoolField,
    FieldSet,
    IntField,
    SpecialCasedDependencies,
    StringField,
    StringSequenceField,
    Target,
)


class PackageV2ShellCommandCommandField(StringField):
    """Shell command to execute in the workspace."""

    alias = "command"
    required = True
    help = "Shell command to run in the repository directory. The command will be executed as `bash -c <command>`."


class PackageV2ShellCommandExecutionDependenciesField(SpecialCasedDependencies):
    """Dependencies to make available during command execution."""

    alias = "execution_dependencies"
    help = (
        "The execution dependencies for this command.\n\n"
        "Dependencies specified here are those required to make the command complete successfully "
        "(e.g. file inputs, packages compiled from other targets, etc), but NOT required to make "
        "the outputs of the command useful. Dependencies that are required to use the outputs "
        "produced by this command should be specified using the `dependencies` field.\n\n"
        "If this field is specified, dependencies from `output_files` and `output_directories` will not be "
        "automatically added. Otherwise, all dependencies will be inferred from those fields."
    )


class PackageV2ShellCommandOutputFilesField(StringSequenceField):
    """Output files generated by the command."""

    alias = "output_files"
    help = (
        "Specify the output files that will be generated by the shell command.\n\n"
        "Paths are relative to the BUILD file's directory and must be within the repository."
    )


class PackageV2ShellCommandOutputDirectoriesField(StringSequenceField):
    """Output directories generated by the command."""

    alias = "output_directories"
    help = (
        "Specify the output directories that will be generated by the shell command.\n\n"
        "Paths are relative to the BUILD file's directory and must be within the repository."
    )


class PackageV2ShellCommandTimeoutField(IntField):
    """Timeout for command execution."""

    alias = "timeout"
    default = 30
    help = "Command execution timeout in seconds."


class PackageV2ShellCommandToolsField(StringSequenceField):
    """Tools to make available during execution."""

    alias = "tools"
    help = (
        "Specify required tools that might be used by the command.\n\n"
        "Pants will search for these tools on the PATH and ensure they are available during execution."
    )


class PackageV2ShellCommandExtraEnvVarsField(StringSequenceField):
    """Extra environment variables to include during execution."""

    alias = "extra_env_vars"
    help = (
        "Additional environment variables to include when running the command.\n\n"
        "Entries are in the form `ENV_VAR=value` to set an explicit value, "
        "or `ENV_VAR` to copy the value from the local environment."
    )


class PackageV2ShellCommandLogOutputField(BoolField):
    """Whether to log command output."""

    alias = "log_output"
    default = False
    help = "Set to true to log the output of the command."


class PackageV2ShellCommand(Target):
    """Run a shell command in the workspace to package files.

    This is similar to `package_shell_command`, but runs the command directly in the
    repository directory (not in a sandbox). Files are created directly in your workspace.

    Example:

        package_v2_shell_command(
            name="generate-requirements",
            command="./generate_requirements.sh",
            output_files=["requirements.txt"],
        )

        docker_image(
            name="my-app",
            dependencies=[":generate-requirements"],
        )

    Run `pants materialize ::` to execute all package_v2_shell_command targets.
    """

    alias = "package_v2_shell_command"
    core_fields = (
        *COMMON_TARGET_FIELDS,
        PackageV2ShellCommandExecutionDependenciesField,
        PackageV2ShellCommandCommandField,
        PackageV2ShellCommandOutputFilesField,
        PackageV2ShellCommandOutputDirectoriesField,
        PackageV2ShellCommandTimeoutField,
        PackageV2ShellCommandToolsField,
        PackageV2ShellCommandExtraEnvVarsField,
        PackageV2ShellCommandLogOutputField,
    )
    help = (
        "Run a shell command in the workspace to package files.\n\n"
        "Similar to package_shell_command, but runs directly in the repository directory."
    )


class PackageV2ShellCommandFieldSet(FieldSet):
    """FieldSet for package_v2_shell_command target."""

    required_fields = (PackageV2ShellCommandCommandField,)

    command: PackageV2ShellCommandCommandField
    execution_dependencies: PackageV2ShellCommandExecutionDependenciesField
    output_files: PackageV2ShellCommandOutputFilesField
    output_directories: PackageV2ShellCommandOutputDirectoriesField
    timeout: PackageV2ShellCommandTimeoutField
    tools: PackageV2ShellCommandToolsField
    extra_env_vars: PackageV2ShellCommandExtraEnvVarsField
    log_output: PackageV2ShellCommandLogOutputField
